name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Gera todo dia
  workflow_dispatch:     # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: tempz-miguelAndrade
          outputs: dist/snake.svg

      - name: Enviar arquivos para o GitHub
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
